### PR TITLE
Extend to accept custom plugins

### PR DESCRIPTION
**Pull request by cdavid15**
We have been using datamaker at work to generate HR data which works great and now we are looking to expand it use to generate more specific business domain data. The issue is these data structures will be something that wouldn't be suitable for inclusion in the project as a core plugins and we don't think a hard fork of the project is the best solution hence this proposal for discussion.

The concept we are striving towards it to continue to use core datamaker project allowing it to expand and grow as necessary but also to allow apps to generate data using their own internal domain specific data generators.  This allow users to create their own private plugins that the core datamaker library simply picks up automatically and parses them like any other template tag when executed.

The concept within this PR has datamaker scan for plugins in the projects current `plugins` folder but also checks for the existence of custom plugins in the `/datamaker/plugins/` folder in the root of the executing application. Within the custom plugins folder a namespace should be used which is where all the plugins would be added. 

This allows for an app to exist with the following directory structure with custom plugins (namespace here is `cd`) :

```
datamaker
└── plugins
    └── cd
        └── type.js
index.js
```

Within `index.js` datamaker would continue to generate data as it does but accepts custom templates as `{{namespace:plugin}}` which indicate that the plugin would exist in the projects root directory `/datamaker/plugins/namespace/plugin.js`:

```js
let dg = require('datamaker')
const template = '{{cd:type}} {{title}} {{firstname}} {{surname}}'
const format = 'none'
const iterations = 5
dg.generate(template, format, iterations)
  .on('data', (d) => { console.log(d) })
  .on('end', (d) => { console.error('Done!') })
```

I haven't updated the readme yet as was keen to have the concept discussed first to see if this is something you think would / could be of use but this idea would certainly allow us to progress using datamaker as our core mock data generator and we would be keen to contribute back with common plugins as and when they are developed.

### CODE REVIEW

**Comment by glynnbird** [comment]
@cdavid15 This is a great idea! 

I assume the plugins you are intending to use would be synchronous? (not going off to a database or anything like that)

I would definitely take this PR with an accompanying README contribution.

I'm glad someone else is finding datamaker useful. I use it all the time :)

**Comment by cdavid15** [comment]
@glynnbird Excellent. Glad you are on board as forking doesn't sit well with us as we should be contributing back to projects which are helpful and will benefit us going forward. 

In our use case these plugins are pretty much identical to what is there but just tailored very specific to our business that makes no point in polluting datamaker with. As a basic example an employee id could be defined as follows:

```js
const integer = require("datamaker/plugins/integer");

module.exports = () => {
  return integer(1000000, 3000000);
};
```

So we would then use it as `{{org:employeeid}} meaning all the devs across the different projects can have a standard way to generate mock employee ids (and not actually care about the format) if they require and it will allow us to build up a catalogue on mock data structures including more complex data objects for people to use. 

I'll tidy the commit up (noticed some typos as well) and then get the readme updated with a section on adding custom plugins and then take it from there.

**Comment by cdavid15** [comment]
@glynnbird - this should be ready to be considered and reviewed now.

**Comment by glynnbird** [comment]
Your branch works great for simple plugins like so:

```
module.exports = () => {
  const x = Math.random()
  return x
}
```

But your example plugin, which loads a native datamaker plugin in doesn't work. The paths are all wrong... the path kind of depends how whether you're:

- code that's using datamaker as a dependency, in which case the path to a built-in plugin would be  path would be something like. `path.join(__dirname, 'node_modules', 'datamaker', 'plugins', 'integer.js')`
- folks using datamaker as a command-line tool would struggle to load a built-in plugin as its directory depends where the datamaker tool is installed. In my case that's `/Users/glynnbird/.npm/lib/node_modules/datamaker/plugins`

what do you think @cdavid15?

**Comment by cdavid15** [comment]
I am not sure 100% sure clear on the 1st issue as my testing the above works ok. I have a version of datamaker with the above changes published to our internal nexus registry and have the test app which appears to run fine (screenshot shows the relevant files):

image

I can then run using the `index.js` as shown in the screenshots which I think would the primary use case. Are you experiencing issues trying this approach then in relation to the use of native datamaker plugin within a custom one?

The other route is through the CLI tool with it installed globally (`employee.datamaker` contains the template shown in `index.js`):

```sh
datamaker -t ./employee.datamaker -i 1
```

or using the version added a project dependency:

```sh
 ./node_modules/@craigdavidson/datamaker/bin/datamaker.bin.js -t ./employee.datamaker -i 1
```

Which results in:

```json
{
  "psi": 2578088,
  "forename": "Elenora",
  "surname": "Cady"
}
```

Don't get me wrong running CLI with custom plugins may not be best use case as you would still need to kick off the execution from within a directory that contained the custom plugins as you pointed out so not sure how many people would use that approach so may not be an issue.

**Comment by glynnbird** [comment]
I think a custom plugin using a pre-built plugin is a bit of an advanced case. Maybe if you're example custom plugin was more simple, we can leave others to solve the paths problem if they need to - there's not very much we (the datamaker devs) can do about it :)

**Comment by glynnbird** [comment]
as it is, a user is going to cut-n-paste your example and it won't work. We need the example in the README to "just work"

**Comment by glynnbird** [comment]
I've changed the PR to use an example plugin that isn't dependent on any other. That gets it out of trouble and makes the example workable.

What do you think @cdavid15 ?

**Comment by cdavid15** [comment]
Think that’s ideal. My intention was for the sample to be a copy and paste within a project that has data maker added but you are right as it would then leave the door open for any dev to use the internal, or other libs (chance or faker etc) if it’s kept simple. 

Could even be a matter of following this up with a link on the readme to a sample project once the new version is published but it is probably overkill to be honest.

**Review by cdavid15 — COMMENTED** [review]
LGTM 👍🏻

**Pull request merged**
